### ISSUE TITLE
Error while running the code?

### ISSUE THREAD

**Issue by itfat** [bamwani/car-counting-and-speed-estimation-yolo-sort-python#10]
Hey, I did everything as written in readme, I downloaded yolo weights, but I am unable to get result, instead I am getting code error. WHy is this?
![p](https://user-images.githubusercontent.com/44062322/103397391-03556500-4b5a-11eb-952e-48dc4afbd67e.png)
This is the error that I get. I am giving it the same input viseo whose link in given in readme.

**Comment by itfat** [comment]
This issue is resolved, Hey I want a suggestion, my counter is not detecting any car just one or maximum two. How can I resolve that?

**Comment by bamwani** [comment]
If you're using another video, then it is most likely because you haven't changed the counter line (```line1```) coordinates. look for the ```intersect``` function where the counter is incremented

**Comment by itfat** [comment]
If you could clarify, from where I can get those values for my video.
You are saying to change thses values.
line1 = [(2370,840), (400, 800)]
line2 = [(2550,820), (670, 780)]
line3 = [(2650,1120), (400, 1090)]
line4 = [(2650,1530), (500, 1520)]
line_speed_start = [(2650,1320), (100, 1260)]
line_speed_end = [(2650,970), (250, 940)]
How did you set them?

**Comment by NZII** [comment]
When i run the commod "Python3 main.py -input /data/video/input/cars.mp4 -output /data/video/output/save_test.mp4 -yolo /yolo" in windows CMD, its nothing to appear. Could you help me?If you see this problem and know how to deal with it,just take your a little time to replay me,and I will appreciate you very much. Looking forward your replay.

**Comment by bamwani** [comment]
@itfat Sorry for the late reply buddy, line 1-4 represents the 4 different camera angle throughout the video. If your video has single cam view and it does not change, Just use the line 1. and comment out the remaining code. You can refer [this](https://www.geeksforgeeks.org/displaying-the-coordinates-of-the-points-clicked-on-the-image-using-python-opencv/) to set the points of line

**Comment by bamwani** [comment]
@Promise-Cc  There could be many reasons behind this. Try printing something at the start of your code to check if the code has atleast started. Check your ram usage while you do this and let me know the data

**Comment by dat1998-coding** [comment]
Hello @bamwani,
When i try to run the code, it stops at:
![Screenshot from 2021-01-22 12-10-40](https://user-images.githubusercontent.com/65003878/105449395-e7e9ff80-5caa-11eb-8b01-2956725e6961.png)
So i tried to replace sort.py by the new sort.py from original author's repo but then, i encouterd the a problem when running video. With video 25 seconds, it outputs 10 seconds video. With 2:16 minutes, it outputs video 12 seconds with the error:
![Screenshot from 2021-01-22 11-18-39](https://user-images.githubusercontent.com/65003878/105445955-b6ba0100-5ca3-11eb-88ea-8503359ca915.png)
I appreciate any helps.

**Comment by NZII** [comment]
> @Promise-cc这背后可能有很多原因。尝试在代码开始时打印一些，以检查代码是否至少已经开始。检查你的公羊使用情况， 而你这样做， 让我知道数据

 

> @Promise-Cc There could be many reasons behind this. Try printing something at the start of your code to check if the code has atleast started. Check your ram usage while you do this and let me know the data

Thank you for your reply, i 'm trying to check it, expecting good news.

**Comment by NZII** [comment]
Hi friends，I‘m run your code and finished, but i have another questions apperenced in my final.csv, which speed_data has not in the final.csv, so i wanna ask you how to solve it, if you have solution  about this question. waitting for your reply, thank you very much.

**Comment by Guttappa1238** [comment]
> Hello @bamwani, When i try to run the code, it stops at: So i tried to replace sort.py by the new sort.py from original author's repo but then, i encouterd the a problem when running video. With video 25 seconds, it outputs 10 seconds video. With 2:16 minutes, it outputs video 12 seconds with the error: I appreciate any helps. ![Screenshot from 2021-01-22 12-10-40](https://user-images.githubusercontent.com/65003878/105449395-e7e9ff80-5caa-11eb-8b01-2956725e6961.png) ![Screenshot from 2021-01-22 11-18-39](https://user-images.githubusercontent.com/65003878/105445955-b6ba0100-5ca3-11eb-88ea-8503359ca915.png)

Hi, Did you solved this error?

**Comment by varshasathya** [comment]
> Hello @bamwani, When i try to run the code, it stops at: ![Screenshot from 2021-01-22 12-10-40](https://user-images.githubusercontent.com/65003878/105449395-e7e9ff80-5caa-11eb-8b01-2956725e6961.png) So i tried to replace sort.py by the new sort.py from original author's repo but then, i encouterd the a problem when running video. With video 25 seconds, it outputs 10 seconds video. With 2:16 minutes, it outputs video 12 seconds with the error: ![Screenshot from 2021-01-22 11-18-39](https://user-images.githubusercontent.com/65003878/105445955-b6ba0100-5ca3-11eb-88ea-8503359ca915.png) I appreciate any helps.

Hi what is the original  author's repo link?
