### ISSUE TITLE
Getting error while running code

### ISSUE THREAD

**Issue by Nisarg-Mehta28** [bamwani/car-counting-and-speed-estimation-yolo-sort-python#14]
I have run the code but they gave me many types of error so can you help me out and I am using the same video only that you are using  and its urgent for me so can you please reply as much fast as you can

**Comment by Nisarg-Mehta28** [comment]
![image](https://user-images.githubusercontent.com/61869445/160258463-3f23c9fc-70a8-4dda-b4ac-9746e8f7af8a.png)
I got this error after installing all the necessary library but then also I got this error 

![image](https://user-images.githubusercontent.com/61869445/160258738-4e4df57e-e312-4f25-98cb-9a7136f77cfc.png)
But I solve that error by writting this code line 

![image](https://user-images.githubusercontent.com/61869445/160258793-537e72a3-a495-4995-ba1c-03b92980e893.png)
So when I tried to run the code by giving them command in terminal I got this type of which is showen in image

So please help me out as soon as you can because its urgent 
Thank you

**Comment by sikhinvc** [comment]
get coco.names file. You can create one .txt file and copy all coco names into it. Then save the file in the same location where your yolo weight file and cfg file is located. Also pass location of folder where yolo cfg and weight file is , not the exact location to cfg while passing through arguments.

**Comment by Nisarg-Mehta28** [comment]
![image](https://user-images.githubusercontent.com/61869445/163677267-527ee976-e6e0-4a6d-8238-cfee4568d959.png)

@sikhinvc see i have done exactly what you have telled me but then also error is there that we can't find the location 

![image](https://user-images.githubusercontent.com/61869445/163677321-1d3c7f77-3c1c-45fe-85dc-17ecb4836979.png)

i have also made the file you can see in above image

**Comment by gitrahulcet1** [comment]
I am getting the same error..
FileNotFoundError: [Errno 2] No such file or directory: 'yolo/coco.names'

I have checked and the file already exists in my Yolo folder.

**Comment by bamwani** [comment]
@white-devil0201 Try entering full path of yolo directory instead of relative path.

**Comment by Nisarg-Mehta28** [comment]
![](https://user-images.githubusercontent.com/61869445/163677267-527ee976-e6e0-4a6d-8238-cfee4568d959.png)
@bamwani I have done exactly that thing in this image
