### ISSUE TITLE
Error while executing code.

### ISSUE THREAD

**Issue by chetan1836** [bamwani/car-counting-and-speed-estimation-yolo-sort-python#16]
When I run the code I'm getting this error.
`Traceback (most recent call last):
  File "F:/MyProjects/TensorFlow/car-counting-and-speed-estimation-yolo-sort-python/code_and_output/main.py", line 265, in <module>
    tracks = tracker.update(dets)`

`File "F:\MyProjects\TensorFlow\car-counting-and-speed-estimation-yolo-sort-python\code_and_output\sort.py", line 207, in update
    matched, unmatched_dets, unmatched_trks = associate_detections_to_trackers(dets,trks)`

`File "F:\MyProjects\TensorFlow\car-counting-and-speed-estimation-yolo-sort-python\code_and_output\sort.py", line 146, in associate_detections_to_trackers`

`    if(d not in matched_indices[:,0]):
TypeError: tuple indices must be integers or slices, not tuple`

Any solutions.

**Comment by vishalrajputt** [comment]
The “TypeError: list indices must be integers, not tuple” error occurs when you specify a tuple as an index value at the end of a list. To solve this problem, make sure that any lists in a list of lists are separated using commas.

**Comment by marunava21** [comment]
Please follow this thread
[https://github.com/abewley/sort/issues/136#issuecomment-864359478](url)

this worked for me
