### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by gitrahulcet1** [bamwani/car-counting-and-speed-estimation-yolo-sort-python#17]
I am getting this error while running the code. how Can I solve this issue.

before I ran into an issue 'invalid index to scalar variable' but I solved it by changing my OpenCV’s version to 4.2
is the current issue due to the maybe wrong version of some package ?

**Comment by bamwani** [comment]
Have you installed opencv-contrib-python library? Tell me if it solves the problem, I'll update the requirements.
