### ISSUE TITLE
Hello, can you explain the steps in more detail?

### ISSUE THREAD

**Issue by byq-luo** [bamwani/car-counting-and-speed-estimation-yolo-sort-python#2]
(yolo) PS G:\ai\car-counting-and-speed-estimation-yolo-sort-python-master\code_and_output> python main.py --input 2.avi --output 3.mp4 --yolo ../yolo
[INFO] loading YOLO from disk...
Traceback (most recent call last):
  File "main.py", line 130, in <module>
    net = cv2.dnn.readNetFromDarknet(configPath, weightsPath)
cv2.error: OpenCV(3.4.2) C:\Miniconda3\conda-bld\opencv-suite_1534379934306\work\modules\dnn\src\darknet\darknet_io.cpp:684: error: (-215:Assertion failed) ifile.is_open() in function 'cv::dnn::darknet::ReadDarknetFromWeightsFile'

(yolo) PS G:\ai\car-counting-and-speed-estimation-yolo-sort-python-master\code_and_output> main.py -input 2.avi -output 3.mp4 -yolo ../yolo
(yolo) PS G:\ai\car-counting-and-speed-estimation-yolo-sort-python-master\code_and_output>
[main 2020-01-10T09:16:10.606Z] update#setState idle
[main 2020-01-10T09:16:41.257Z] update#setState checking for updates
[main 2020-01-10T09:17:02.533Z] [Error: net::ERR_CONNECTION_CLOSED]
[main 2020-01-10T09:17:02.536Z] update#setState idle

**Comment by bamwani** [comment]
opencv is not able to locate your yolo model. Use ```--yolo ./yolo```,  instead of  ```--yolo ../yolo```. you are using double```.```

**Comment by bamwani** [comment]
@byq-luo  You might not have the yolo weights file. I've added a bash file to download the same. Give it a try.

**Comment by byq-luo** [comment]
> @byq-luo You might not have the yolo weights file. I've added a bash file to download the same. Give it a try.

Thank you.
