### ISSUE TITLE
Below command in not running in gitbash

### ISSUE THREAD

**Issue by notinrange** [bamwani/car-counting-and-speed-estimation-yolo-sort-python#21]
Python3 main.py -input /path/to/video/file.avi -output /path/for/output/video/file.avi -yolo /path/to/YOLO/directory/

**Comment by notinrange** [comment]
It shows this type of error "main.py: error: unrecognized arguments: /input.avi /output.avi yolo"

**Comment by bamwani** [comment]
Check your python version. This project was developed in 3.6.9
