### ISSUE TITLE
How can run it on GPU ?

### ISSUE THREAD

**Issue by JiaqiJin** [bamwani/car-counting-and-speed-estimation-yolo-sort-python#3]

**Comment by bamwani** [comment]
you can refer to this article to run opencv's implementation of YOLO with GPU:
https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/

**Comment by JiaqiJin** [comment]
> you can refer to this article to run opencv's implementation of YOLO with GPU:
> https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/

Thx so much
