### ISSUE TITLE
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'

### ISSUE THREAD

**Issue by sgq123** [bamwani/car-counting-and-speed-estimation-yolo-sort-python#7]
Hi, When I run the main.py ,I met an error,
  File "/home/shangguoqian/anaconda3/envs/car_counting/lib/python3.6/site-packages/numba/targets/codegen.py", line 608, in _init
    tm = target.create_target_machine(**tm_options)
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'

I check the version of numba ,it is 0.38.1, just what the readme said.
Could you tell me what should I do to solve this problem,thanks so much!

**Comment by bamwani** [comment]
Hi @sgq123 , I have added a template to raise an issue. Please follow the same so I can understand your issue better.
Also I recommend creating a Python virtual environment for this project

**Comment by sgq123** [comment]
> Hi @sgq123 , I have added a template to raise an issue. Please follow the same so I can understand your issue better.
> Also I recommend creating a Python virtual environment for this project

Thanks @bamwani 
When I go to code_and_output directory
Run “python main.py -input traffic_video.avi -output results.avi -yolo ../yolo”
See error as below 
![error](https://user-images.githubusercontent.com/30233362/86129066-bba34180-bb14-11ea-9d29-719a060511be.png)
I think maybe it is the result of version of numba, so I checked conda list as below:
![conda_list](https://user-images.githubusercontent.com/30233362/86129132-cbbb2100-bb14-11ea-96b9-d32817a1e40b.png)
The version of numba is the same as your version 0.38.1,so I don’t know how to solve it.
My system is ubuntu 16.04
And my pip version is 9.0.1,python version is 3.6.2 as below
![pip_v](https://user-images.githubusercontent.com/30233362/86129206-eab9b300-bb14-11ea-9ab9-618fd0619694.png)

And the project structure is as below:
![dir1](https://user-images.githubusercontent.com/30233362/86129267-01f8a080-bb15-11ea-9766-a39672e8afba.png)
![dir2](https://user-images.githubusercontent.com/30233362/86129278-04f39100-bb15-11ea-8d6f-823bae5449d2.png)
Thanks again!

**Comment by bamwani** [comment]
@sgq123 Update pip to latest version, and install numba without mentioning any version. i.e. Try with the latest version.
Tell me if this works, I'll update the requirements

**Comment by sgq123** [comment]
> @sgq123 Update pip to latest version, and install numba without mentioning any version. i.e. Try with the latest version.
> Tell me if this works, I'll update the requirements

Thank you so much! It works ! I update pip to version 20.1.1 and numba is version 0.50.1
