### ISSUE TITLE
The output video is unclear 

### ISSUE THREAD

**Issue by jaiidas** [bamwani/car-counting-and-speed-estimation-yolo-sort-python#8]
the output video shows like the attached image. I can't figure out what is the problem or where can I change the height and width of the video
<img width="1088" alt="Screen Shot 2020-07-14 at 4 21 54 PM" src="https://user-images.githubusercontent.com/49152345/87430608-2319c080-c5ee-11ea-8113-d6727c53dfb2.png">

**Comment by bamwani** [comment]
@jaiidas 
Looks like you are new to OpenCV.
```
cv2.putText(frame, "LANES ARE NUMBERED FROM LEFT TO RIGHT STARTING FROM 1", (100,50), cv2.FONT_HERSHEY_DUPLEX, 2.0, (0, 0, 255), 5)
```
here 2.0 is the font scale. [Ref](https://www.geeksforgeeks.org/python-opencv-cv2-puttext-method/)

also, I have not scaled the video frames. Looking at your video quality, I'll suggest you the same too.

**Comment by jaiidas** [comment]
I mean the video is like it has been cropped cause the original video is like attached image
<img width="1159" alt="Screen Shot 2020-07-14 at 7 01 01 PM" src="https://user-images.githubusercontent.com/49152345/87448336-60894880-c604-11ea-93c2-0ebd33dd1f0f.png">
